### ISSUE TITLE
Fix Unit Testing Link

### ISSUE THREAD

**Issue by suyashkumar** [mlp6/Medical-Software-Design#128]
https://github.com/mlp6/Medical-Software-Design/blob/master/Lectures/UnitTestingCI.md
should be travis-ci.org not .com !

**Comment by mlp6** [comment]
I thought those were being merged into one-in-the-same (?):
https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps

**Comment by suyashkumar** [comment]
I'll close this out and update my assignment instructions to point to .com!
