### ISSUE TITLE
Update Schedule with Web Service Lectures

### ISSUE THREAD

**Issue by suyashkumar** [mlp6/Medical-Software-Design#20]
I plan to have draft lecture titles/topics ready to teach what's needed for the web service portion of the class, and will add those lecture titles into the syllabus. @mlp6 There are only a couple "TBD" slots open for these, so we may need to move around and condense some existing lectures if you're open to it (e.g. maybe we cover regular expressions along with an earlier lecture)! We should sync on the strategy there, and I'd love to get thoughts on your end.

**Comment by ad12** [comment]
Regex probably won't be as intuitive for students, even though it is easy to work with on python. I could hold a session for more clarification and in depth use of regex if we end up collapsing the lectures
