### ISSUE TITLE
Class Repository Layout

### ISSUE THREAD

**Issue by suyashkumar** [mlp6/Medical-Software-Design#22]
Looking through the layout of this repo, was thinking it might make sense to logically separate out F16 and F17 class work to make it easier to navigate. What're thoughts on a layout like:
```
F16
    - assignments
        - assignment01
        - ...
    - lectures
    - syllabus/schedule
    - supporting files / misc

F17 
    - assignments
       - assignment01
        - ...
    - lectures
    - syllabus/schedule
    - supporting files / misc
```

I can execute on this refactor (don't worry, I'll use `git mv` to move things around so file histories are linked) if folks approve of something like this (@mlp6).

**Comment by mlp6** [comment]
I think that I have most of the existing material reorganized.  Should be easier to add new material in this structure.
