### ISSUE TITLE
Writeup Travis CI Article

### ISSUE THREAD

**Issue by suyashkumar** [mlp6/Medical-Software-Design#29]
I'm thinking about writing up a Travis CI tutorial that steps through setting up an anaconda project for Travis CI (anaconda definitely makes things harder...)

**Comment by mlp6** [comment]
I usually have both (1) `environment.yml` and a (2) `requirements.txt` file in my repos, using the latter for the Travis CI.  Conda was easier to use with `gitlab-runner` b/c there is a Conda docker image that can be used... I've only used Travis with their language-specific images.

**Comment by suyashkumar** [comment]
Ah I see--but there are some cases where there are anaconda packages that are not on pip right? Let me see if I can simplify the anaconda CI process at all, but generally it shouldn't be so terrible (I'd just install ~~anaconda~~ miniconda using `apt-get` then proceed with creating the virtualenv, etc). I'll try it out, hopefully the install/build time doesn't take too long

**Comment by suyashkumar** [comment]
(personally I stick with python/pip for my projects, but seems like most of the class is using anaconda so I think it's worth the effort to make it work! Will report back here).

**Comment by mlp6** [comment]
One of the issues that I hit with python/pip last semester was that numpy/scipy can take a long time to build, and that dominates the CI runtime.  Via conda, the packages come in pre-built, so minutes of test time goes down to seconds.

**Comment by suyashkumar** [comment]
hmm that makes sense...it would be nice if pip cached prebuilt packages or if the travis cluster did...

**Comment by mlp6** [comment]
Can Travis use Docker images?

**Comment by suyashkumar** [comment]
[Yep](https://docs.travis-ci.com/user/docker/), it'll just use Docker pull to pull an image down from docker hub...would then have to docker exec to enter the runtime and clone and run the target repository. Definitely possible, but may be a little hand-wavy for students if they haven't heard of docker yet (which is okay). 

In general I don't think installing miniconda and then just running the env setup commands they already know will be way more time consuming here. I'll do some empirical tests and let you know!

**Comment by mlp6** [comment]
Cool beans... maybe we can motivate Docker in a few weeks as a way to streamline this virtual env process, and then let them advance their knowledge of containers from there if they are so inclined.

**Comment by suyashkumar** [comment]
[A build](https://travis-ci.org/suyashkumar/bme590-conda-ci) with installing miniconda and some deps (that included numpy) took 1min 13 secs, so not bad.

I'll annotate the `.travis.yml` file to describe what some of the unfamiliar lines are doing

**Comment by davidbradway** [comment]
Not sure if this is helpful for `pip` in Travis? 
https://docs.travis-ci.com/user/caching/#pip-cache

**Comment by mlp6** [comment]
@suyashkumar should we close this given the resources that we have in place?

**Comment by mlp6** [comment]
I think this is now covered with: https://github.com/mlp6/Medical-Software-Design/blob/master/Lectures/UnitTestingCI.md#continuous-integration-travis-ci
