### ISSUE TITLE
GitHub Classroom

### ISSUE THREAD

**Issue by mlp6** [mlp6/Medical-Software-Design#86]
https://classroom.github.com/

We should look more closely to see if assignments generated through this would play nicer with Travis CI integration, etc.  I have a feeling we are re-inventing the wheel some, and possibly less gracefully.

**Comment by mlp6** [comment]
https://github.com/blog/2500-my-first-semester-using-github-at-rice-university

An example implementation...

**Comment by suyashkumar** [comment]
Hm...seems pretty useful, particularly the teams functionality for assigning group project (I did not see how those teams get formed though, in the sample video). Travis CI integration for testing/grading could be pretty great, but we likely have to decide if we want the test conditions we check against to be public (travis-ci org would be public, right?)

**Comment by suyashkumar** [comment]
it seems like teams get created based on students who show up at the invite url?
https://classroom.github.com/g/K6jDzzz0

**Comment by suyashkumar** [comment]
ah, it seems that students are asked to create a team for the first assignment
<img width="1077" alt="screen shot 2018-02-14 at 12 01 57 am" src="https://user-images.githubusercontent.com/6299853/36188503-62a12e7c-111a-11e8-8144-833bac71c871.png">

**Comment by suyashkumar** [comment]
seems odd that we cannot reuse existing teams. I created one here via the classroom prompts:
https://github.com/orgs/Duke-BME-Design/teams/test-team

**Comment by mlp6** [comment]
@suyashkumar happy with this for the second assignment?
